name: Pandoc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/core:latest
        with:
          args: >-
            --defaults=wp.yaml
            --to=latex
            --output=template/layer3-whitepaper.tex
      - uses: actions/cache@v2
        name: Tectonic Cache
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: tectonic template/layer3-whitepaper.tex --outdir output
      - uses: actions/upload-artifact@v2
        with:
          name: layer3-whitepaper.pdf
          path: output/layer3-whitepaper.pdf
      - uses: actions/upload-artifact@v2
        with:
          name: pdf.log.json
          path: log/pdf.log.json
